In [1]:
import warnings

warnings.filterwarnings("ignore")

In [3]:
import rpy2.robjects as ro

In [4]:
r = ro.r
r['source']('teste_r.R')
filter_target = ro.globalenv['filter_target']
filter_target

<rpy2.robjects.functions.SignatureTranslatedFunction object at 0x000001EB92AC3740> [RTYPES.CLOSXP]
R classes: ('function',)

In [5]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

df = load_iris()
df = pd.DataFrame(data=np.c_[df['data'], df['target']], 
                  columns=df['feature_names']+['target'])

In [6]:
df.sample(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
149,5.9,3.0,5.1,1.8,2.0
107,7.3,2.9,6.3,1.8,2.0
7,5.0,3.4,1.5,0.2,0.0
146,6.3,2.5,5.0,1.9,2.0
33,5.5,4.2,1.4,0.2,0.0

In [7]:
#df.to_csv('iris.csv')
#df = pd.read_csv('iris.csv')

In [8]:
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter

In [9]:
with localconverter(ro.default_converter + pandas2ri.converter):
    r_from_pd = ro.conversion.py2rpy(df)
r_from_pd

<rpy2.robjects.vectors.DataFrame object at 0x000001EB92C39EC0> [RTYPES.VECSXP]
R classes: ('data.frame',)
[FloatSe..., FloatSe..., FloatSe..., FloatSe..., FloatSe...]
  sepal length (cm): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB96260700> [RTYPES.REALSXP]
  sepal width (cm): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB962AEA40> [RTYPES.REALSXP]
  petal length (cm): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB96271580> [RTYPES.REALSXP]
  petal width (cm): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB962AEC00> [RTYPES.REALSXP]
  target: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB962AED80> [RTYPES.REALSXP]

In [10]:
type(r_from_pd)

rpy2.robjects.vectors.DataFrame

In [11]:
df_result_r = filter_target(r_from_pd, 1)
df_result_r

<rpy2.robjects.vectors.DataFrame object at 0x000001EB96296500> [RTYPES.VECSXP]
R classes: ('data.frame',)
[FloatSe..., FloatSe..., FloatSe..., FloatSe..., FloatSe...]
  sepal length (cm): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB962AEA80> [RTYPES.REALSXP]
  sepal width (cm): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB962B3FC0> [RTYPES.REALSXP]
  petal length (cm): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB962B35C0> [RTYPES.REALSXP]
  petal width (cm): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB962B2380> [RTYPES.REALSXP]
  target: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x000001EB962B2500> [RTYPES.REALSXP]

In [12]:
df_result = pandas2ri.rpy2py(df_result_r)
df_result

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
50,7.0,3.2,4.7,1.4,1.0
51,6.4,3.2,4.5,1.5,1.0
52,6.9,3.1,4.9,1.5,1.0
53,5.5,2.3,4.0,1.3,1.0
54,6.5,2.8,4.6,1.5,1.0
55,5.7,2.8,4.5,1.3,1.0
56,6.3,3.3,4.7,1.6,1.0
57,4.9,2.4,3.3,1.0,1.0
58,6.6,2.9,4.6,1.3,1.0
59,5.2,2.7,3.9,1.4,1.0
60,5.0,2.0,3.5,1.0,1.0
61,5.9,3.0,4.2,1.5,1.0
62,6.0,2.2,4.0,1.0,1.0
63,6.1,2.9,4.7,1.4,1.0
64,5.6,2.9,3.6,1.3,1.0
65,6.7,3.1,4.4,1.4,1.0
66,5.6,3.0,4.5,1.5,1.0
67,5.8,2.7,4.1,1.0,1.0
68,6.2,2.2,4.5,1.5,1.0
69,5.6,2.5,3.9,1.1,1.0
70,5.9,3.2,4.8,1.8,1.0
71,6.1,2.8,4.0,1.3,1.0
72,6.3,2.5,4.9,1.5,1.0
73,6.1,2.8,4.7,1.2,1.0
74,6.4,2.9,4.3,1.3,1.0
75,6.6,3.0,4.4,1.4,1.0
76,6.8,2.8,4.8,1.4,1.0
77,6.7,3.0,5.0,1.7,1.0
78,6.0,2.9,4.5,1.5,1.0
79,5.7,2.6,3.5,1.0,1.0
80,5.5,2.4,3.8,1.1,1.0
81,5.5,2.4,3.7,1.0,1.0
82,5.8,2.7,3.9,1.2,1.0
83,6.0,2.7,5.1,1.6,1.0
84,5.4,3.0,4.5,1.5,1.0
85,6.0,3.4,4.5,1.6,1.0
86,6.7,3.1,4.7,1.5,1.0
87,6.3,2.3,4.4,1.3,1.0
88,5.6,3.0,4.1,1.3,1.0
89,5.5,2.5,4.0,1.3,1.0
90,5.5,2.6,4.4,1.2,1.0
91,6.1,3.0,4.6,1.4,1.0
92,5.8,2.6,4.0,1.2,1.0
93,5.0,2.3,3.3,1.0,1.0
94,5.6,2.7,4.2,1.3,1.0
95,5.7,3.0,4.2,1.2,1.0
96,5.7,2.9,4.2,1.3,1.0
97,6.2,2.9,4.3,1.3,1.0
98,5.1,2.5,3.0,1.1,1.0
99,5.7,2.8,4.1,1.3,1.0